/**
 * Example Generated Types
 *
 * This file shows what types will be generated when you run:
 * npm run generate:types
 *
 * The actual generated file will be created at:
 * src/types/api-generated.ts
 *
 * DO NOT EDIT THIS FILE - it's just an example!
 * Run `npm run generate:types` to generate real types from your backend.
 */

/**
 * Example of generated OpenAPI types
 * These types are automatically generated from your NestJS backend's Swagger/OpenAPI spec
 */

export interface paths {
  "/api/v1/auth/sign-in/email": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        401: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/api/v1/auth/get-session": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["SessionResponse"] | null;
          };
        };
      };
    };
  };

  "/api/v1/auth/sign-up/email": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
            name: string;
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["AuthResponse"];
          };
        };
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };

  "/api/v1/permissions/my-permissions": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": Record<string, boolean>;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    User: {
      id: string;
      email: string;
      name: string;
      emailVerified: boolean;
      image?: string;
      createdAt: string;
      updatedAt: string;
      role: "ADMIN" | "MODERATOR" | "EDITOR" | "USER";
    };

    Session: {
      token: string;
      expiresAt: string;
    };

    AuthResponse: {
      user: components["schemas"]["User"];
      session: components["schemas"]["Session"];
    };

    SessionResponse: {
      user: components["schemas"]["User"];
      session: components["schemas"]["Session"];
    };

    ErrorResponse: {
      statusCode: number;
      message: string;
      error?: string;
    };

    PermissionCheckResponse: {
      hasPermission: boolean;
    };
  };
}

/**
 * USAGE EXAMPLES:
 *
 * 1. Extract specific types:
 *    type User = components["schemas"]["User"];
 *    type Session = components["schemas"]["Session"];
 *
 * 2. Extract request/response types:
 *    type LoginRequest = paths["/api/v1/auth/sign-in/email"]["post"]["requestBody"]["content"]["application/json"];
 *    type LoginResponse = paths["/api/v1/auth/sign-in/email"]["post"]["responses"]["200"]["content"]["application/json"];
 *
 * 3. Use in service methods:
 *    async function login(data: LoginRequest): Promise<LoginResponse> {
 *      const response = await apiClient.post("/api/v1/auth/sign-in/email", data);
 *      return response.data;
 *    }
 *
 * 4. Type-safe API client:
 *    function createApiClient<T extends keyof paths>(endpoint: T) {
 *      return {
 *        get: () => apiClient.get(endpoint),
 *        post: (data: paths[T]["post"]["requestBody"]["content"]["application/json"]) =>
 *          apiClient.post(endpoint, data)
 *      };
 *    }
 */

/**
 * BENEFITS:
 *
 * 1. Type Safety:
 *    - TypeScript will error if backend response shape changes
 *    - Autocomplete for all API endpoints and responses
 *    - Catch breaking changes at compile time
 *
 * 2. Zero Maintenance:
 *    - Types update automatically when backend changes
 *    - No manual type definitions needed
 *    - Always in sync with backend
 *
 * 3. Better Developer Experience:
 *    - IntelliSense shows all available endpoints
 *    - Autocomplete for request/response fields
 *    - Inline documentation from backend
 *
 * 4. Prevents Bugs:
 *    - Can't access fields that don't exist
 *    - Can't send wrong data shape
 *    - Type errors before runtime errors
 */

/**
 * TO GET STARTED:
 *
 * 1. Make sure your NestJS backend has Swagger configured:
 *    - Install @nestjs/swagger
 *    - Set up SwaggerModule in main.ts
 *    - Expose /api-json endpoint
 *
 * 2. Start your backend:
 *    cd backend && npm run dev
 *
 * 3. Generate types:
 *    cd frontend && npm run generate:types
 *
 * 4. Import and use:
 *    import type { components } from "@/types/api-generated";
 *    type User = components["schemas"]["User"];
 *
 * 5. Keep types up to date:
 *    - Run npm run generate:types when backend changes
 *    - Add to pre-build script (already configured)
 *    - Add to CI/CD pipeline
 */
